/**
 * PDF Report Service - Generate monthly expense reports
 */

const PDFDocument = require('pdfkit');
const Transaction = require('../models/Transaction');

/**
 * Generate monthly PDF report
 */
async function generateMonthlyReport(userId, userName) {
  try {
    const now = new Date();
    const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
    const endOfMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0);

    // Fetch data
    const [transactions, categoryData, monthlyTotal] = await Promise.all([
      Transaction.findAllByUser(userId, {
        startDate: startOfMonth.toISOString().slice(0, 10),
        endDate: endOfMonth.toISOString().slice(0, 10),
      }),
      Transaction.expenseByCategory(
        userId,
        startOfMonth.toISOString().slice(0, 10),
        endOfMonth.toISOString().slice(0, 10)
      ),
      Transaction.totalExpense(
        userId,
        startOfMonth.toISOString().slice(0, 10),
        endOfMonth.toISOString().slice(0, 10)
      ),
    ]);

    // Filter expenses only
    const expenses = transactions.filter(t => t.type === 'expense');

    // Create PDF
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];

    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => {});

    // Header
    doc.fontSize(24).fillColor('#6366F1').text('Trackify', 50, 50);
    doc.fontSize(16).fillColor('#475569').text('Monthly Expense Report', 50, 80);
    doc.fontSize(12).fillColor('#64748b').text(
      `${startOfMonth.toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}`,
      50,
      105
    );

    // User info
    doc.fontSize(10).fillColor('#1e293b').text(`User: ${userName}`, 50, 140);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 50, 155);

    // Summary
    doc.fontSize(14).fillColor('#1e293b').text('Summary', 50, 190);
    doc.fontSize(12).fillColor('#475569');
    doc.text(`Total Expenses: ₹${Number(monthlyTotal).toLocaleString()}`, 50, 215);
    doc.text(`Total Transactions: ${expenses.length}`, 50, 235);

    // Category breakdown
    if (categoryData.length > 0) {
      doc.fontSize(14).fillColor('#1e293b').text('Category Breakdown', 50, 270);
      doc.fontSize(10).fillColor('#64748b');
      let y = 295;
      categoryData.slice(0, 10).forEach((cat, idx) => {
        doc.text(`${idx + 1}. ${cat.category}: ₹${Number(cat.total).toLocaleString()}`, 50, y);
        y += 18;
      });
    }

    // Transactions table header
    doc.fontSize(14).fillColor('#1e293b').text('Transactions', 50, y + 20);
    doc.fontSize(9).fillColor('#64748b');
    doc.text('Date', 50, y + 45);
    doc.text('Category', 150, y + 45);
    doc.text('Amount', 350, y + 45);
    doc.moveTo(50, y + 60).lineTo(550, y + 60).stroke();

    // Transactions
    let tableY = y + 70;
    expenses.slice(0, 30).forEach((t) => {
      if (tableY > 700) {
        doc.addPage();
        tableY = 50;
      }
      doc.fontSize(8).fillColor('#1e293b');
      doc.text(new Date(t.transaction_date).toLocaleDateString(), 50, tableY);
      doc.text(t.category, 150, tableY);
      doc.text(`₹${Number(t.amount).toLocaleString()}`, 350, tableY);
      tableY += 15;
    });

    // Footer
    const pageCount = doc.bufferedPageRange().count;
    for (let i = 0; i < pageCount; i++) {
      doc.switchToPage(i);
      doc.fontSize(8).fillColor('#94a3b8').text(
        `Page ${i + 1} of ${pageCount} | Generated by Trackify`,
        50,
        doc.page.height - 30,
        { align: 'center' }
      );
    }

    // Chart data (JSON for frontend)
    const chartData = {
      category_expense: categoryData,
      monthly_total: monthlyTotal,
      transaction_count: expenses.length,
    };

    doc.end();

    return new Promise((resolve, reject) => {
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(chunks);
        resolve({ pdfBuffer, chartData });
      });
      doc.on('error', reject);
    });
  } catch (err) {
    console.error('[PDFService] Error:', err.message);
    throw err;
  }
}

module.exports = { generateMonthlyReport };
